language: node_js
node_js:
- 12.8.1
os:
- linux
sudo: false
addons:
  ssh_known_hosts: {TARGET_IP}
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_e6cc0fb2b8da_key -iv $encrypted_e6cc0fb2b8da_iv
  -in travis.enc -out travis -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn build
after_script:
- rsync -av public/ root@${TARGET_IP}:/data/blog/public
branches:
  only:
  - dev
